[platformio]
default_envs = m5stack-atoms3

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM6
monitor_port = COM6
build_flags =
  -D SENSOR_PIN=5
  -D SENSOR_VS=5.06
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
upload_protocol = esptool
